name: "Bug Report"
description: "File a bug report"

labels:
  - a:bug

body:

  - type: input
    id: version
    attributes:
      label: "Version"
      description: |
        What version of GH-Lint are you running and how?
      placeholder: |
        ghlint 1.2.3 | action@v1.2.3

  - type: textarea
    id: repro
    attributes:
      label: "Reproduction steps"
      description: |
        What steps did you take to reproduce this bug?
        A fully functional minimal example is highly appreciated.
      value: |
        1. File `.github/workflows/x.yml` with the following content:
           ```yaml
           on: push
           jobs:
             repro:
               runs-on: ubuntu-latest
               steps:
                 - run: echo "Problem!"
           ```

        2. Run `ghlint` with the following arguments:
           ```shell
           ghlint --console .github/workflows/x.yml
           ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: |
        What did you expect to happen when you followed the reproduction steps?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      description: |
        What did you see instead? Please include any error messages / output / screenshot.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: |
        Is there anything else that you think might help us understand the problem?
        What is the impact of this bug?
        Have you found any workarounds?
