name: "CI Report"

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

jobs:
  test-results:
    name: "Publish Test Results"
    # Only run when there's relevant result with some hope (in decreasing order) of having the artifacts necessary.
    if: ${{ contains(fromJSON('["success","failure","timed_out","cancelled"]'), github.event.workflow_run.conclusion) }}
    runs-on: ubuntu-24.04
    timeout-minutes: 3

    permissions:
      # actions/download-artifact
      actions: read
      # EnricoMi/publish-unit-test-result-action
      checks: write

    steps:

      - name: "Download 'Event File' artifact."
        uses: actions/download-artifact@v6
        with:
          name: 'Event File'
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          path: .

      - name: "Download 'Unit Test Results' artifact."
        uses: actions/download-artifact@v6
        with:
          name: 'Unit Test Results'
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          path: results

      - name: "Publish 'Unit Results' check suite."
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          event_file: event.json
          check_name: '🔔 Test: Unit Results'
          comment_mode: off
          check_run_annotations: none
          report_individual_runs: true
          test_changes_limit: 0
          action_fail_on_inconclusive: true
          files: |
            results/**/build/test-results/*/TEST-*.xml
